# Generated by Django 6.0.2 on 2026-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('all', 'All'), ('department', 'Department'), ('branch', 'Branch'), ('specific', 'Specific')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('policy', 'Policy'), ('event', 'Event'), ('urgent', 'Urgent'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], max_length=50)),
                ('target_audience', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('branches', models.ManyToManyField(blank=True, to='organization.branch')),
                ('departments', models.ManyToManyField(blank=True, to='organization.department')),
            ],
        ),
    ]
