# Generated by Django 6.0.2 on 2026-02-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('total_experience_years', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('career_site', 'Career Site'), ('job_portal', 'Job Portal'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_round', models.CharField(blank=True, choices=[('phone_screening', 'Phone Screening'), ('technical_interview', 'Technical Interview'), ('hr_interview', 'HR Interview'), ('final_interview', 'Final Interview'), ('other', 'Other')], max_length=50, null=True)),
                ('interview_type', models.CharField(blank=True, choices=[('in_person', 'In-person'), ('video_call', 'Video Call'), ('phone_call', 'Phone Call')], max_length=50, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('interview_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
                ('result', models.CharField(blank=True, choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], max_length=20, null=True)),
                ('offered_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('response_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interview_schedules', to='organization.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_code', models.CharField(max_length=50, unique=True)),
                ('number_of_openings', models.IntegerField()),
                ('employment_type', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('min_experience_years', models.IntegerField()),
                ('max_experience_years', models.IntegerField()),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='organization.branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='organization.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='organization.designation')),
            ],
        ),
    ]
