# Generated by Django 6.0.2 on 2026-02-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('general', 'General'), ('constructive', 'Constructive')], max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('weightage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('review_deadline', models.DateField()),
                ('status', models.CharField(choices=[('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual')], default='quanterly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('self', 'Self Review'), ('peer', 'Peer Review'), ('manager', 'Manager Review'), ('subordinate', 'Subordinate Review')], default='self', max_length=20)),
                ('technical_skills_rating', models.IntegerField(blank=True, null=True)),
                ('communication_skills_rating', models.IntegerField(blank=True, null=True)),
                ('teamwork_rating', models.IntegerField(blank=True, null=True)),
                ('leadership_rating', models.IntegerField(blank=True, null=True)),
                ('problem_solving_rating', models.IntegerField(blank=True, null=True)),
                ('punctuality_rating', models.IntegerField(blank=True, null=True)),
                ('overall_rating', models.IntegerField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged')], default='draft', max_length=20)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='organization.employee')),
            ],
        ),
    ]
