# Generated by Django 6.0.2 on 2026-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('nominated', 'Nominated'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completion_certificate', models.FileField(blank=True, null=True, upload_to='training_certificates/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('credential_id', models.CharField(max_length=100)),
                ('credential_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('compliance', 'Compliance'), ('leadership', 'Leadership'), ('other', 'Other')], max_length=100)),
                ('training_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person'), ('hybrid', 'Hybrid'), ('external', 'External'), ('workshop', 'Workshop')], max_length=100)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trainer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_participants', models.IntegerField()),
                ('cost_per_participant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_going', 'Ongoing')], default='scheduled', max_length=20)),
            ],
        ),
    ]
